using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace Sql_Widget.Views
{
	/// <summary>
	/// Interaction logic for ResultWindow.xaml
	/// </summary>
	public partial class ResultWindow : Window
	{
		public ResultWindow()
		{
			InitializeComponent();
		}

		private void DataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
		{
			myDataGrid.Columns.ToList().ForEach(column => column.Width = DataGridLength.SizeToHeader);
		}
	}
}
